### ISSUE TITLE
Sidebar Disappeared

### ISSUE THREAD

**Issue by AlbertLee125** [SECQUOIA/pyomo-summer-ws#6]
After I replaced the old footer, 'Bernal Research Group' with 'SECQUOIA Research Group', the sidebar of the https://secquoia.github.io/pyomo-summer-ws/intro.html website has been disappeared.

**Comment by ZedongPeng** [comment]
Previously, we built the JupiterBook locally and pushed the html files to Github.
You didn't build the project in your last PR and manually changed the HTML files.
Try to set up the GitHub actions according to the JupiterBook documentation.
https://jupyterbook.org/en/stable/publish/gh-pages.html

**Comment by AlbertLee125** [comment]
Since the issue is resolved I will close this with comments.
